# Configuration for Rasa NLU.
language: en

pipeline:
  - name: text-normalizer.TextNormalizer
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
    intent_tokenization_flag: False
    intent_split_symbol: "+"
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: DucklingEntityExtractor
    url: http://0.0.0.0:8000
    locale: en_GB
    dimensions: ["time","phone-number"]
  #other components
  - name: FallbackClassifier
    threshold: 0.7


# Configuration for Rasa Core.
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: RulePolicy
